'use strict';
let exerciseType='coding',labSolution=false,traceStep=0,labAnswers=['',''],labChecked=false;
let labDraft='',labChecks=[];let labStorage=true;
try{const saved=JSON.parse(localStorage.getItem('exam02-lab-v1'));if(saved){labDraft=typeof saved.draft==='string'?saved.draft:'';labChecks=Array.isArray(saved.checks)?saved.checks.filter(x=>Number.isInteger(x)&&x>=0&&x<6):[];}}catch{labStorage=false;}
function saveLab(){try{localStorage.setItem('exam02-lab-v1',JSON.stringify({draft:labDraft,checks:labChecks}));}catch{labStorage=false;}if($('draft-status'))$('draft-status').textContent=labStorage?'Draft saved in this browser.':'Browser storage unavailable; draft kept for this session.';}
function renderExercises(){
 const {coding,pseudocode}=ExamExercises;const c=exerciseType==='coding',exercise=c?coding:pseudocode;
 $('content').innerHTML=`<div class="lab-tabs" aria-label="Written exercise"><button class="secondary ${c?'selected-tab':''}" id="coding-tab" aria-pressed="${c}">Write C++</button><button class="secondary ${!c?'selected-tab':''}" id="pseudo-tab" aria-pressed="${!c}">Complete pseudocode</button></div><article class="card"><div class="card-meta"><span class="pill">CHAPTER 2 · ${c?'VALUE SWAP':'NODE SWAP'}</span><span>${c?'WRITE & SELF-REVIEW':'2 MISSING LINES'}</span></div><div class="card-body lab-body"><h3 class="quiz-question">${escape(exercise.title)}</h3><p class="definition lab-prompt">${formatProse(exercise.prompt)}</p><pre class="example">${escape(exercise.signature)}</pre>${c?codingWorkspace():pseudoWorkspace()}</div></article>`;
 $('coding-tab').onclick=()=>{exerciseType='coding';renderExercises();};$('pseudo-tab').onclick=()=>{exerciseType='pseudocode';renderExercises();};
 if(c)bindCoding();else bindPseudo();
}
function codingWorkspace(){
 const c=ExamExercises.coding;
 return `<details class="lab-examples"><summary>Examples & edge cases</summary>${c.examples.map((e,i)=>{const out=ExamExercises.swapValues(e.calling,e.parameter);return `<pre class="example">CASE ${i+1}\nBefore calling:   ${escape(e.calling.join(' ')||'(empty)')}\nBefore parameter: ${escape(e.parameter.join(' ')||'(empty)')}\nAfter calling:    ${escape(out.calling.join(' ')||'(empty)')}\nAfter parameter:  ${escape(out.parameter.join(' ')||'(empty)')}</pre>`;}).join('')}</details><label class="draft-label" for="code-draft">Your function body<textarea id="code-draft" spellcheck="false" autocomplete="off" placeholder="// Write only the missing body here…">${escape(labDraft)}</textarea></label><p id="draft-status" class="tip">${labStorage?'Draft saved in this browser.':'Browser storage unavailable; draft kept for this session.'}</p><p class="lab-notice">This is a writing and self-review workspace. Your draft is not compiled or automatically graded.</p><div class="lab-actions"><button class="primary" id="show-coding-solution">${labSolution?'Hide':'Reveal'} reference solution</button></div>${labSolution?`<section class="lab-solution"><h3>Reference body</h3><pre class="example">${escape(c.solution)}</pre><p class="tip">${formatProse('The temporary is an integer value, not a pointer. The guard protects both accesses; no `else` block or relinking is needed.')}</p><p class="tip">${formatProse(c.note)}</p></section>`:''}<h3 class="rubric-title">Check your work</h3><p class="tip">Use this checklist to compare your draft with the requirements. Checking a box records your own review.</p><div class="rubric">${c.checks.map((text,i)=>`<label><input type="checkbox" data-rubric="${i}" ${labChecks.includes(i)?'checked':''}><span>${formatProse(text)}</span></label>`).join('')}</div>`;
}
function bindCoding(){
 $('code-draft').oninput=e=>{labDraft=e.target.value;saveLab();};
 $('code-draft').onkeydown=e=>{if(e.key==='Tab'){e.preventDefault();const input=e.target,start=input.selectionStart,end=input.selectionEnd;input.setRangeText('    ',start,end,'end');labDraft=input.value;saveLab();}};
 $('show-coding-solution').onclick=()=>{labSolution=!labSolution;renderExercises();};
 document.querySelectorAll('[data-rubric]').forEach(input=>input.onchange=()=>{const i=Number(input.dataset.rubric);labChecks=labChecks.filter(x=>x!==i);if(input.checked)labChecks.push(i);saveLab();});
}
function pseudoWorkspace(){
 const p=ExamExercises.pseudocode;
 return `<pre class="example pseudo-lines">${escape(p.lines.join('\n'))}</pre><div class="blank-answers">${p.blanks.map((b,i)=>`<label for="blank-${i}">Missing line ${b.line}<select id="blank-${i}"><option value="">Choose a statement…</option>${b.options.map((s,j)=>`<option value="${j}" ${labAnswers[i]===String(j)?'selected':''}>${escape(s)}</option>`).join('')}</select><pre class="example selected-statement" id="statement-${i}">${labAnswers[i]!==''?escape(b.options[Number(labAnswers[i])]):'Your selected statement appears here.'}</pre></label>`).join('')}</div><div class="lab-actions"><button class="primary" id="check-blanks">Check both lines</button><button class="secondary" id="clear-blanks">Try again</button></div><div id="blank-feedback" role="status">${labChecked?blankFeedback():''}</div><section class="pointer-lab"><h3>Trace the pointer changes</h3><p class="tip">${formatProse(p.note)}</p><div class="lab-actions"><button class="secondary" id="trace-prev" ${traceStep===0?'disabled':''}>← Previous step</button><span class="tip">${traceStep} / 9</span><button class="secondary" id="trace-next" ${traceStep===9?'disabled':''}>Next step →</button></div><div id="trace-diagram">${diagram()}</div></section>`;
}
function blankFeedback(){return ExamExercises.pseudocode.blanks.map((b,i)=>`<div class="feedback"><h3>${Number(labAnswers[i])===b.answer?'✓ Correct':'Revisit'} · Line ${b.line}</h3><pre class="example">${escape(b.options[b.answer])}</pre><p>${formatProse(b.explanation)}</p></div>`).join('');}
function bindPseudo(){
 ExamExercises.pseudocode.blanks.forEach((b,i)=>$('blank-'+i).onchange=e=>{labAnswers[i]=e.target.value;labChecked=false;$('blank-feedback').innerHTML='';$('statement-'+i).textContent=e.target.value===''?'Your selected statement appears here.':b.options[Number(e.target.value)];});
 $('check-blanks').onclick=()=>{if(labAnswers.some(a=>a==='')){$('blank-feedback').innerHTML='<p class="lab-notice">Choose a statement for both missing lines first.</p>';return;}labChecked=true;$('blank-feedback').innerHTML=blankFeedback();};
 $('clear-blanks').onclick=()=>{labAnswers=['',''];labChecked=false;traceStep=0;renderExercises();};
 $('trace-prev').onclick=()=>{traceStep--;renderExercises();};$('trace-next').onclick=()=>{traceStep++;renderExercises();};
}
function diagram(){
 const {steps,traceState}=ExamExercises;const state=traceState(traceStep),previous=traceState(Math.max(0,traceStep-1));
 const groups=traceStep===9?[[9,2,3,4,5],[6,7,8,1]]:[[1,2,3,4,5],[6,7,8,9]];
 const link=(value)=>value===null?'null':'Node'+value;
 return `<div class="trace-stage" aria-live="polite"><p class="definition">${formatProse(steps[traceStep].text)}</p><pre class="example">${escape(steps[traceStep].code)}</pre><p class="tip">Pointer roots: calling <code class="inline-code">first</code> → Node${state.first}, <code class="inline-code">last</code> → Node${state.last}; parameter <code class="inline-code">first</code> → Node${state.paramFirst}, <code class="inline-code">last</code> → Node${state.paramLast}; <code class="inline-code">current</code> → ${link(state.current)}</p>${groups.map((group,i)=>`<p class="eyebrow">${traceStep===9?(i?'PARAMETER LIST':'CALLING LIST'):(i?'ORIGINAL PARAMETER NODES':'ORIGINAL CALLING NODES')}</p><div class="node-row">${group.map(id=>{const node=state.nodes[id],old=previous.nodes[id];return `<div class="trace-node"><strong>Node${id}</strong><small>data: ${id}</small><span class="${old.prev!==node.prev?'changed-link':''}">prev → ${link(node.prev)}</span><span class="${old.next!==node.next?'changed-link':''}">next → ${link(node.next)}</span></div>`;}).join('')}</div>`).join('')}<p class="tip">Highlighted links changed in this step. Nodes retain their original identity and data. ${traceStep===9?'Final forward lists: 9 2 3 4 5 and 6 7 8 1. Reverse lists: 5 4 3 2 9 and 1 8 7 6.':'Node cards stay in their original groups until the final step; read their links and the pointer roots to track the temporary state.'}</p></div>`;
}
