(function(root){
'use strict';
const lessons=[
{id:'deduction',title:'One type or two types?',topic:'Templates',summary:'A repeated T means one shared type. T1 and T2 can be different types.',steps:['For printPair(T first, T second), the compiler must deduce the same T from both arguments.','printPair(10, 20) uses int; printPair(3.14, 2.71) uses double. printPair(5, 4.5) fails: int and double conflict. Test each call separately; a program containing the failing call will not run.','With two type parameters, printPair(5, 4.5) works: T1 is int and T2 is double.'],code:'template<typename T>\nvoid printPair(T first, T second) {\n    std::cout << first << " and " << second;\n}\n\n// Alternative: independent types\ntemplate<typename T1, typename T2>\nvoid printPair(T1 first, T2 second) {\n    std::cout << first << " and " << second;\n}',note:'These are two alternative teaching examples. Read the template header before predicting output.'},
{id:'explicit',title:'Explicit types and conversions',topic:'Templates',summary:'Types inside <...> are supplied explicitly. Remaining types can still be deduced.',steps:['printPair<int>(\'A\', 3.14) fixes T1 as int and deduces T2 as double. On an ASCII system, it prints 65 and 3.14.','printPair<double, int>(2.5, 8.9) fixes both types. 8.9 converts to int by dropping its fractional part: output is 2.5 and 8.','In multiplyData(T value, int multiplier), only value determines T. The second argument converts to int. The calls `multiplyData(5.5, 3)`, `multiplyData(\'A\', 2)`, and `multiplyData(10, 4.5)` print 16.5, 130, and 40 respectively on an ASCII system.'],code:'template<typename T>\nvoid multiplyData(T value, int multiplier) {\n    std::cout << value * multiplier << std::endl;\n}\n\nmultiplyData(10, 4.5); // multiplier becomes 4',note:'65 for \'A\' assumes ASCII, in these examples. C++ does not require that character encoding. Deduction does not simply convert conflicting argument types to make one T work.'},
{id:'unused',title:'The template type that cannot be guessed',topic:'Templates',summary:'A type parameter that appears nowhere in the function parameters cannot be deduced from these arguments.',steps:['T1 comes from val1 and T2 from val2. T3 has no matching function parameter and no default.','processValues(1, 10, 20) and processValues(3, "Hello", 42) fail because T3 remains unknown.','processValues<double, int, char>(2, 3.14, 5) works: all three template types are supplied. The output is `2: 3.14 and 5`. The leading 2 is count, followed by the literal separator ": ", then val1 and val2. T3 is char, but no function argument has type T3.'],code:'template<typename T1, typename T2, typename T3>\nvoid processValues(int count, T1 val1, T2 val2) {\n    std::cout << count << ": " << val1\n              << " and " << val2 << std::endl;\n}',note:'Do not match the three template types to the three function arguments by position. count is always int; T3 is unused.'},
{id:'const-ref',title:'Read-only parameters can accept different types',topic:'Templates',summary:'const references avoid object copies and allow reading without changing the argument through that reference.',steps:['processData(42, 36.5) deduces T1 = int and T2 = double.','The parameters bind to the arguments without copying them into separate parameter objects. The output is 42 and 36.5.','Different types work because this function has two independent type parameters. const does not force the types to match.'],code:'template<typename T1, typename T2>\nvoid processData(const T1& val1, const T2& val2) {\n    std::cout << val1 << " and " << val2 << std::endl;\n}',note:'For large class objects, avoiding a copy can help. For small types such as int, passing by value can be equally suitable.'},
{id:'headers',title:'Where does template<typename T> belong?',topic:'Templates',summary:'Inside a class template, ordinary members already have the class’s T. Outside it, repeat the template header.',steps:['Inside template<typename T> class DArray, an ordinary member like addElement(const T&) uses the class’s T; do not add another template<typename T> above it.','For an ordinary member definition outside that class template, write template<typename T> and qualify the name with DArray<T>::.','This applies even when the return type is int: getNumOfElements still belongs to DArray<T>. Constructors also use DArray<T>::DArray(...).'],code:'template<typename T>\nclass DArray {\n    int numOfElements = 0;\npublic:\n    int getNumOfElements() const;\n};\n\ntemplate<typename T>\nint DArray<T>::getNumOfElements() const {\n    return numOfElements;\n}',note:'These rules apply to ordinary members. A member with its own additional template parameters needs its own template header.'},
{id:'member-templates',title:'A regular class can contain template functions',topic:'Templates',summary:'A class does not have to be a template for one of its functions to be a template.',steps:['MyClass is a regular class. printHello() is an ordinary function and needs no template header.','processData<T>() is a member function template. It introduces its own T, even inside the class.','Each separate member function template needs its own header. A header above processFirst does not introduce T for processSecond.'],code:'class MyClass {\npublic:\n    void printHello() { }\n\n    template<typename T>\n    void processFirst(T value) { }\n\n    template<typename T1, typename T2>\n    void processThird(T1 first, T2 second) { }\n};',note:'Each templated function introduces its own template parameters. It does not apply to ordinary members such as printHello().'},
{id:'visibility',title:'Make template definitions available',topic:'Templates',summary:'The compiler normally needs the template body where it creates a version for a particular type.',steps:['A declaration alone says the function exists. The template definition provides the code needed to generate a version such as Pair<int>.','One possible layout includes both TemplateClass.h and TemplateClass.cpp in main.cpp. That can expose definitions if the implementation is arranged that way.','A common alternative is to put definitions in the header, or have the header include a .tpp implementation file. Explicit instantiation is another approach for a fixed set of types.'],code:'// Common layout\n// Pair.h\n#ifndef PAIR_H\n#define PAIR_H\ntemplate<typename T>\nclass Pair { /* declarations */ };\n#include "Pair.tpp" // template definitions\n#endif\n\n// main.cpp\n#include "Pair.h"',note:'Including a .cpp is a layout choice, not a universal C++ requirement. In that layout, avoid separately compiling the included implementation in a way that creates duplicate non-template definitions.',link:'https://eel.is/c++draft/temp.pre'},
{id:'abstraction',title:'Write the algorithm once',topic:'Templates',summary:'Algorithm abstraction separates the main steps from details such as the exact data type.',steps:['A function template expresses the same algorithm for several suitable types.','The compiler creates a version for each type you actually use.','“Any type” means a type that supports the operations in the body. A multiplication template will not automatically work for std::string.'],code:'template<typename T>\nT twice(T value) {\n    return value + value;\n}\n// int: addition; std::string: concatenation',note:'Focus on what the algorithm needs from T. Template syntax does not make unsupported operations valid.'},
{id:'vector',title:'Vector size is different from capacity',topic:'Vectors & DArray',summary:'Size counts existing elements. Capacity is space available before reallocation.',steps:['std::vector<int> v(5) creates five elements, each initialized to 0. v[0] is a valid element.','An empty vector followed by reserve(5) still has size 0. Its capacity is at least 5; no elements were added.','Do not use vec[0] after reserve alone. Use push_back(10) to add an element, or resize(5) to create five elements.'],code:'std::vector<int> v(5); // size 5; v[0] == 0\nstd::vector<int> vec;\nvec.reserve(5);        // size 0; capacity >= 5\nvec.push_back(10);     // size 1; vec[0] == 10',note:'The portable guarantee is capacity >= 5. Accessing vec[0] when size is 0 is undefined behavior; it need not produce a visible crash.',link:'https://eel.is/c++draft/vector.capacity'},
{id:'objects',title:'Which object owns this array?',topic:'Vectors & DArray',summary:'a and otherArray.a are different pointer members, belonging to different objects.',steps:['Inside a member function, a means this->a: the pointer in the object that called the function.','otherArray.a means the pointer in the parameter object. a[idx] and otherArray.a[idx] read values at the same index in the two arrays.','The == compares element values. Comparing a == otherArray.a would compare addresses instead. idx must be valid for both arrays.'],code:'bool DArray::compareElemAtIdx(\n    const DArray& otherArray, int idx) const {\n    return a[idx] == otherArray.a[idx];\n}',note:'A class member may access private members of another object of the same class. A const member function does not automatically make memory reached through a raw pointer const.'},
{id:'insert',title:'Insert immediately before the last node',topic:'Linked lists',summary:'The new node becomes second-to-last. The existing last node stays last.',steps:['Assume at least two nodes. Save last->getPrev(), the old second-to-last node.','Create the new node with prev = secondToLast and next = last.','Update both neighbors: secondToLast->setNext(newNode) and last->setPrev(newNode). Then increment count.'],code:'// Precondition: count >= 2\nvoid DoublyList::insertSecondToLast(int newData) {\n    DLLNode* secondToLast = last->getPrev();\n    DLLNode* newNode = new DLLNode(\n        newData, secondToLast, last);\n    secondToLast->setNext(newNode);\n    last->setPrev(newNode);\n    ++count;\n}',note:'This snippet assumes at least two nodes; shorter lists need separate handling.'}
];
const extra=[];
function q(id,lesson,prompt,options,answer,explanation,code='',hint='Check the relevant rule, then trace one step at a time.'){
 const l=lessons.find(l=>l.id===lesson);extra.push({id:'slides-'+id,chapter:l.topic==='Linked lists'?'2':'3–4',sourceQuestion:id,category:l.topic,prompt,options,answer,explanation,code,codeChoices:false,relatedTerms:[l.topic==='Linked lists'?'Doubly linked list':'Class template'],hint,source:l.title,lessonId:lesson});
}
q('same','deduction','Evaluate this call on its own. Does it compile?', ['Yes: prints 5 and 4.5','Yes: prints 5 and 4','No: the two arguments deduce different types for T','No: templates cannot accept double'],2,'The first argument deduces int and the second double. One T cannot be both. No output is produced.','template<typename T>\nvoid printPair(T first, T second);\nprintPair(5, 4.5);');
q('two','deduction','Which types are deduced for this call?',['T1 = int, T2 = double','Both are double','Both are int','The call fails'],0,'T1 and T2 are independent, so each is deduced from its own argument.','template<typename T1, typename T2>\nvoid printPair(T1 first, T2 second);\nprintPair(5, 4.5);');
q('partial','explicit','Assume ASCII. What does this call print?',['A and 3.14','65 and 3.14','65 and 3','Compilation error'],1,'<int> fixes only T1. A converts to int (65 in ASCII); T2 is deduced as double.',lessons[0].code.split('// Alternative: independent types\n')[1]+"\nprintPair<int>('A', 3.14);");
q('convert','explicit','What does the call print?',['2.5 and 8.9','2 and 8','2.5 and 8','Compilation error'],2,'Both types are explicit. Converting 8.9 to int drops the fraction; it does not round to 9.',lessons[0].code.split('// Alternative: independent types\n')[1]+'\nprintPair<double, int>(2.5, 8.9);');
q('multiplier','explicit','What does multiplyData(10, 4.5) print?',['45','40','Compilation error','44.5'],1,'T is int from 10. The fixed int multiplier receives 4, so the result is 10 * 4.',lessons[1].code);
q('char','explicit',"Assume ASCII. What does multiplyData('A', 2) print?",['AA','A2','130','Compilation error'],2,'T is char. Multiplication promotes the character to its numeric value: 65 * 2 = 130.',lessons[1].code.split('\n\nmultiplyData')[0]);
q('unused','unused','Why does this call fail?',['The count must be a template type','T3 cannot be deduced from the function arguments','T1 and T2 must match','Three arguments are too many'],1,'No parameter uses T3 and no default is supplied. The compiler cannot infer it.',lessons[2].code+'\nprocessValues(1, 10, 20);');
q('specified','unused','Evaluate this call on its own. What happens?',['Fails because T3 is unused','Prints 2: 3.14 and 5','Prints 2: 3 and a character','Prints 2: 3.14 and char'],1,'All types are supplied. count is int, val1 is double, val2 is int. No function parameter uses T3.',lessons[2].code+'\nprocessValues<double, int, char>(2, 3.14, 5);');
q('read-only','const-ref','What happens for processData(42, 36.5)?',['Fails: const references reject literals','Fails: both arguments must have the same type','Prints 42 and 36.5','Prints 42 and 36'],2,'const references can bind to these arguments. The two type parameters are independent.',lessons[3].code);
q('inside','headers','Inside a class template, does this ordinary getter need another template<typename T> directly above it?',['Yes, every function needs one','No, it already uses the class template’s T','Only when T is int','No, because const removes the template'],1,'The class header introduces T for ordinary members defined inside the class.','template<typename T>\nclass Box {\n    T value;\npublic:\n    T get() const { return value; }\n};');
q('outside','headers','The getter returns int. Why is the template header still needed outside the class?',['Every int function is a template','It belongs to DArray<T>, a class template','const requires a template header','It is optional'],1,'The class is parameterized by T, even though this particular member returns int.',lessons[4].code);
q('regular','member-templates','Which function needs its own template header in this regular class?',['Both printHello and processFirst','Only printHello','Only processFirst','Neither'],2,'processFirst introduces its own T. printHello is an ordinary member.',lessons[5].code);
q('visible','visibility','A header has only template declarations. The template bodies are in a separate implementation file. What must normally be available where an implicit instantiation is needed?',['Only the class name','The template definitions','A second main function','A runtime type string'],1,'The compiler needs the definitions to generate code for the chosen type. Header definitions or an included implementation are common solutions; explicit instantiation is an alternative.');
q('abstraction','abstraction','What does a function template help you do?',['Use every possible type with every operation','Write an algorithm once for types supporting its operations','Avoid compiling the function body','Automatically convert every argument to int'],1,'The algorithm is reused, but each chosen type must support the operations in its body.');
q('reserve','vector','After this code, which statement is correct?',['size is 5; vec[0] is 0','size is 0; capacity is at least 5','size is 0; capacity must be exactly 0','size is 5; elements are uninitialized'],1,'reserve creates room for future elements. It does not add elements.','std::vector<int> vec;\nvec.reserve(5);');
q('access','vector','Which next line adds the value 10 correctly?',['vec[0] = 10;','vec.push_back(10);','vec.reserve(10);','vec.capacity() = 10;'],1,'push_back creates an element. Index 0 does not exist yet after reserve alone.','std::vector<int> vec;\nvec.reserve(5);');
q('owner','objects','What does the return expression compare?',['The two array addresses','The two elements at index idx','The two capacities','The two object addresses'],1,'The [] operator selects an element from each array; == compares the values.',lessons[9].code);
q('index','objects','What must be true before comparing a[idx] and otherArray.a[idx]?',['idx must equal both capacities','idx must be a valid element index in both arrays','The arrays must have identical addresses','Both arrays must have the same length'],1,'The arrays may have different lengths. idx must be nonnegative and smaller than each array’s element count.');
q('insert','insert','After inserting before the last node, which pointer still points to the same node?',['last','last->getPrev()','The old second-to-last node’s next','All three'],0,'last stays at the existing tail. Its prev and the old second-to-last node’s next now point to the new node.',lessons[10].code);
q('short-list','insert','Why does this insertion snippet require at least two nodes?',['new only works with two nodes','With one node, last->getPrev() is nullptr','count cannot become 2','The last node must be deleted'],1,'On a one-node list, secondToLast is nullptr. Calling setNext through it would be invalid. An empty list also makes last invalid to dereference.',lessons[10].code);
if(typeof module!=='undefined')module.exports={lessons,questions:extra};else{root.LectureStudio={lessons,questions:extra};root.CoursePractice.questions.push(...extra);}
})(typeof window!=='undefined'?window:globalThis);
